version: '3.0'
 
services:
  rasa:
    build:
      context: rasa
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
      - ./.config:/app/.config
    command: >
      run
      --port 5005
      --jwt-method HS256
      --jwt-secret ${JWT_SECRET}
      --auth-token '${RASA_TOKEN}'
      --cors "*"
      --credentials credentials.yml
      --debug
    depends_on:
      - actions
      - mongo

  actions:
    build:
      context: actions
    volumes:
      - ./actions:/app/actions
    command: 'start --actions actions --auto-reload  --debug'
    environment:
      HOST : "${HOST}"
      PORT : "${PORT}"
      USER : "${USER}"
      PASSWORD : "${PASSWORD}"
      DATABASE : "${DATABASE}"
    ports:
      - 5055:5055
    links:
      - mongo

  web:
    build: 
      context: web
    ports: 
      - "3000:3000"
    depends_on:
      - rasa
    links:
      - rasa

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${PASSWORD}"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${PASSWORD}"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - rasa
      - actions
      - web
      - mongo
      - mongo-express